package ui

const (
	COLOR_STATUS_SUCCESS      = "#32CD32"
	COLOR_STATUS_REDIRECT     = "#FFA500"
	COLOR_STATUS_ERROR        = "#A52A2A"
	COLOR_PROGRESS_GRADIENT_A = "#FF7CCB"
	COLOR_PROGRESS_GRADIENT_B = "#FDFF8C"
	COLOR_SEPARATOR           = "#7F8C8D"
	COLOR_FOOTER_BACKGROUND   = "#0D1117"
	COLOR_FOOTER_FONT         = "#FFFFFF"
)
